// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using comero.Data;

namespace comero.Migrations
{
    [DbContext(typeof(ComeroContext))]
    [Migration("20211225071915_seedDataMig")]
    partial class seedDataMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("comero.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "توضیحات",
                            Name = "دسته بندی اول"
                        },
                        new
                        {
                            Id = 2,
                            Description = "توضیحات",
                            Name = "دسته بندی دوم"
                        },
                        new
                        {
                            Id = 3,
                            Description = "توضیحات",
                            Name = "دسته بندی سوم"
                        },
                        new
                        {
                            Id = 4,
                            Description = "توضیحات",
                            Name = "دسته بندی چهارم"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
